import Head from 'next/head'
import Image from 'next/image'
import HeroSlider from '../components/home/HeroSlider'
import HorrorMovie from '../components/home/HorrorMovie'
import MovieofTheYear from '../components/home/MovieofTheYear'
import PopularMovie from '../components/home/PopularMovie'
import RecomendedMovie from '../components/home/RecomendedMovie'
import styles from '../styles/Home.module.css'

export default function Home({ movies }) {
  console.log(movies)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSlider />
      <PopularMovie />
      <HorrorMovie />
      <MovieofTheYear />
      <RecomendedMovie />
    </div>
  )
}
