import Head from 'next/head'
import Image from 'next/image'
import HeroSlider from '../components/home/HeroSlider'
import LatestMovies from '../components/home/LatestMovies'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <HeroSlider />
      <LatestMovies />

    </div>
  )
}
